# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Puget Sound Psychotherapy
subtitle: Your awsome subtitle
headline: Puget Sound Psychotherapy & Psychiatry
homepage_header: http://pugetpsychotherapy.com/images/background-mountains.jpg
email: intake@pugetpsychotherapy.com
cta:
  email: intake@pugetpsychotherapy.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

locations:
  - title: "SF"
    street: '837 Larkin St.'
    city_state_zip: 'San Francisco, CA 94109'
    phone: '+1 207-555-5555'
  - title: "LA"
    street: '1111 Manor Way'
    city_state_zip: 'Los Angeles, CA 90048'
    phone: '+1 323-555-5555'
  - title: "London"
    street: "11 Downey St."
    city_state_zip: "London, UK"
    phone: "+44 0 5555-5555"

  - title: "Tokyo"
    street: "1982 Flangan Rd."
    city_state_zip: "Shinjuku, Tokyo"
    phone: "+99 5555-5555"

# Build settings
markdown: kramdown
theme: tachyons-blocks
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
